feat: Grant Detail View (#31)
* basic layout

* midway into grant detail page

* lg grant detail view done

* added responsivess to grant detail view

* update yarn.lock

* re-fix explorer card z-index

* updated props for grant view

* fix linting errors on TransactionSeries.tsx

* add dockerfile and readd lorem-ipsum

* fix: removed lorem-ipsum from the root package.json

* rename explorer to explore

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -1,15 +1,59 @@
-FROM node:12-alpine
+### Copied from https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
 
-WORKDIR /opt/app
+# Install dependencies only when needed
+FROM node:16-alpine AS deps
+# Node alpine is streamlined and does not include these dependencies
+RUN apk add --no-cache libc6-compat git openssh
+WORKDIR /app
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+elif [ -f package-lock.json ]; then npm ci; \
+elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+else echo "Lockfile not found." && exit 1; \
+fi
+
+
+# Rebuild the source code only when needed
+FROM node:16-alpine AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
+
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN yarn build
+
+# Production image, copy all the files and run next
+FROM node:16-alpine AS runner
+WORKDIR /app
 
 ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+ENV NEXT_TELEMETRY_DISABLED 1
 
-COPY package*.json ./
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
-RUN npm ci 
+# You only need to copy next.config.js if you are NOT using the default configuration
+COPY --from=builder /app/next.config.js ./
+COPY --from=builder /app/public ./public
+COPY --from=builder /app/package.json ./package.json
 
-COPY . /opt/app
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
-RUN npm install --dev && npm run build
+USER nextjs
 
-CMD [ "npm", "start" ]
+EXPOSE 3000
+
+ENV PORT 3000
+
+CMD ["node", "server.js"]
